---
name: Default
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos, ubuntu]
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*
      - uses: actions/cache@v5
        with:
          path: ~/.cargo/registry
          key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustc --version
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: pnpm run check
      - run: cargo fmt -- --check
      - run: cargo check --locked
      - run: cargo clippy --locked
      - run: cargo test --locked
      - run: cargo build --locked --release --verbose
